name: lteenb-lool
version: '2017-02-10'
summary: LTE Software eNodeB
description: |
  LTEENB is a LTE base station (eNodeB) implemented entirely in software
  and running on a PC. The PC generates a baseband signal which is sent
  to a radio front end doing the digital to analog conversion. The
  reverse is done for the reception.
grade: devel
confinement: devmode

apps:
  lteenb:
    command: lteenb-launcher
    daemon: simple
  systune:
    command: lte_init.sh
  set-license:
    command: set-license
  set-rfbackend:
    command: set-rfbackend

parts:
  # prebuilt LTEENB
  lteenb:
    plugin: dump
    source: ../lteenb-linux-2017-02-10.tar.gz
    # don't copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    # needed by lteenb binaries
    stage-packages: [ libsctp1, libuhd003, ]
    stage:
      - config/
      - lib*.so
      - lteenb*
      - lte_init.sh
      - trx_*.so
      - usr/lib/*/*.so.*
  # LimeSDR TRX backend
  trx-lms:
    plugin: make
    source: ../trx_lms7002m-linux-2017-02-10.tar.gz
    # don't automatically copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    build-packages: [ liblimesuite-dev, ]
    stage-packages: [ liblimesuite17.01-1, ]
    install: |
      cp -f trx_*.so $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/config
      rm -rf $SNAPCRAFT_PART_INSTALL/config/limeSDR
      cp -rf config-limeSDR $SNAPCRAFT_PART_INSTALL/config/limeSDR
    stage:
      - config/
      - lib/*/*.so.*
      - trx_*.so
      - usr/lib/*/*.so.*
  # snap integration bits
  glue:
    plugin: dump
    source: glue
    install: |
      # ship static symlink pointing to writable dir
      mkdir -p $SNAPCRAFT_PART_INSTALL/config
      ln -sf /var/snap/lteenb-lool/current/rf_driver \
          $SNAPCRAFT_PART_INSTALL/config/rf_driver

